### ISSUE TITLE
Description in UI needs typo fix and update

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-whitepages#21]
It currently says: 

Use Whitepages Pro Phone Intelligence to get data insights into a number’s reputation, as well as activity, such as call volumes, type of phone and types of spam. The Caller Identification integration identifies the owner of a phone number and append (----> please update to appends) name, address, demographic data and more to your leads. More info.

But we need to indicate that address validation is an option, too. To get the ball rolling - perhaps this could work: 

The Address Validation integration standardizes mailing address data. It also appends details about the location, such as whether an address is deliverable.

@alexj, what do you think?

**Comment by alexj** [comment]
Good call. I like where you're going with this and have modified the entire text block:
>Phone Intelligence provides insights into a number’s reputation, as well as activity, such as call volumes and type of phone. Caller Identification identifies the owner of a phone number and appends name, address, demographic data and more. Address Validation standardizes mailing addresses and appends additional data about the location, such as whether an address is deliverable. More info. More info

Thoughts?

**Comment by ros3bud** [comment]
That sounds great to me. Just running with what you wrote, what about: "it also offers insight into the location such as whether an address is deliverable or why it is not." ?

**Comment by alexj** [comment]
Instead of "and appends additional data about the location, such as whether an address is deliverable."? That works. I'm a bit concerned with the overall text length, so we'll have to see what it looks like in the UI.

**Comment by ros3bud** [comment]
Yeah, I was thinking instead of. We shall see indeed and can adjust if it gets crowded.

**Comment by justinwinslow** [comment]
<img width="951" alt="screen shot 2015-11-03 at 1 39 18 pm" src="https://cloud.githubusercontent.com/assets/1864534/10919410/4f862002-8230-11e5-96cc-8b8530e71d45.png">

**Comment by justinwinslow** [comment]
Take 2:

<img width="940" alt="screen shot 2015-11-03 at 1 47 19 pm" src="https://cloud.githubusercontent.com/assets/1864534/10919620/72a1f092-8231-11e5-91f3-24d904248454.png">

**Comment by ros3bud** [comment]
Looks great by me. :)
