### ISSUE TITLE
Error parsing location

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-whitepages#26]
From the production logs: 

```
TypeError: Cannot read property 'latitude' of null
```

I assume this is because of a failure to properly null check here:

https://github.com/activeprospect/leadconduit-integration-whitepages/blob/master/src/caller_id.coffee#L97-L98

**Comment by cgrayson** [comment]
Fixed in [PR #27](https://github.com/activeprospect/leadconduit-integration-whitepages/pull/27/files#diff-6eaf839da80d2174c78521667c419919).
